name: Auto Deploy to VPS

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Начинаем обновление..."
            cd /var/www/reg.iamdaemon.tech
            
            git pull origin main
            
            # Исправляем права (ПРАВИЛЬНО: www-data)
            chown -R www-data /var/www/reg.iamdaemon.tech
            find /var/www/reg.iamdaemon.tech -type f -exec chmod 644 {} +
            find /var/www/reg.iamdaemon.tech -type d -exec chmod 755 {} +
            
            systemctl reload nginx
            
            echo "✅ Готово!"